name: victor-frankenstein
services:
  victor-frankenstein:
    cpu_shares: 90
    command:
      - npm
      - start
    deploy:
      resources:
        limits:
          memory: 7939M
    environment:
      - APPLICATION_ID=
      - DISCORD_TOKEN=
      - NODE_VERSION=20.19.5
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SERVER_ID=
      - TMDB_API_KEY=
      - TMDB_BEARER_TOKEN=
      - YARN_VERSION=1.22.22
    image: victor-frankenstein:1.0.0
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/victor-frankenstein
        target: /usr/src/app
    x-casaos:
      envs:
        - container: PATH
          description:
            en_us: ""
        - container: NODE_VERSION
          description:
            en_us: ""
        - container: YARN_VERSION
          description:
            en_us: ""
      image: ""
      ports:
        - container: "8080"
          description:
            en_us: ""
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    hostname: ""
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
  developer: unknown
  hostname: ""
  icon: ""
  image: null
  index: /
  is_uncontrolled: false
  main: victor-frankenstein
  port_map: ""
  scheme: http
  store_app_id: victor-frankenstein
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  thumbnail: ""
  tips:
    custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  title:
    custom: ""
    en_us: victor-frankenstein
